### ISSUE TITLE
Integrate Dependabot to Project

### ISSUE THREAD

**Issue by SudharakaP** [OpenArchitex/AccoTech#16]
For automatically updating dependencies we need to add [Dependabot](https://dependabot.com/) to this project.

Steps: 

1) Similar to what we have created in OpenLearnr (https://github.com/OpenArchitex/OpenLearnr/blob/develop/.github/dependabot.yml) we need to add a `dependabot.yml` file to the `.github` folder. 

2) Copy the above file but instead of using `maven` we should use `gradle` as that is what we use in this project.

**Comment by JuanVqz** [comment]
it sounds good, would you like to assign me this issue? Can I start it after tomorrow?

**Comment by SudharakaP** [comment]
@JuanVqz : Unfortunately this is already assigned to another person. But I will create more issues on this repo and in the OpenArchitex organization in the coming days; so stay tuned. 😄

**Comment by JuanVqz** [comment]
> @JuanVqz : Unfortunately this is already assigned to another person. But I will create more issues on this repo and in the OpenArchitex organization in the coming days; so stay tuned. 😄

No worries, thank you!

**Comment by JuanVqz** [comment]
@SudharakaP sorry, I got another one! thank you!
