### ISSUE TITLE
Add Code of Conduct to Project

### ISSUE THREAD

**Issue by SudharakaP** [OpenArchitex/AccoTech#18]
We should add the Code of Conduct to the project. The template should be `Contributor Covenant`. This can be automatically added through the Github Insights tab.

**Comment by ayushi-1408** [comment]
Hey! Can I work on this issue?

**Comment by SudharakaP** [comment]
@ayushi-1408 : This is already assigned to another person unfortunately. But we'll be opening more issues on this repo and organization; so stay tuned. 😄

**Comment by SudharakaP** [comment]
@ayushi-1408 : Are you still interested in this one? If so you can work on it. 😄

**Comment by ayushi-1408** [comment]
Yes Sure
