### ISSUE TITLE
Enable PWA Support

### ISSUE THREAD

**Issue by SudharakaP** [OpenArchitex/AccoTech#21]
We should enable PWA (Progressive Web Application) support for this web application. This can be easily done by un-commenting the following section in `index.html`

https://github.com/OpenArchitex/AccoTech/blob/46ba0b06a922f780ae3c44912f188644415120ee/src/main/webapp/index.html#L84-L94

We can test this using [Chrome's LightHouse tools](https://developers.google.com/web/tools/lighthouse/)

**Comment by DevanshCodes** [comment]
Can I work on this?

**Comment by SudharakaP** [comment]
@DevanshCodes : Yes feel free to submit a PR. Thank you. 👍🏼

**Comment by DevanshCodes** [comment]
Hey @SudharakaP can you take a look at the PR?
