### ISSUE TITLE
Create Jumboton on Homepage

### ISSUE THREAD

**Issue by SudharakaP** [OpenArchitex/AccoTech#3]
We need to create a Jumbotron in the homepage. Some considerations; 

- [ ] Have changing images similar to https://accountingtoronto.ca/ or https://cherishcakes.ca/ with text on top. 

- [ ] Add a link to the contact section (which will be done in different issue) and perhaps the services section (#4 ); we need to give the contact section and services section more visibility as this is an accounting website and clients will want to contact them for more info.

**Comment by faithghlee** [comment]
I can take this up if you don't mind. Did client provide images for jumbotron? I am assuming you want images of Toronto or we should source images without copyright issues?

**Comment by SudharakaP** [comment]
@faithghlee : Sure you can take it. The one needs creativity as it's the first thing most customers will see. No need to provide images; we can find a lot of free high quality images off the internet; for example the ones we use at cherishcakes and pythonsinhala are all oss. Let me point you to some website which has images; 

This one has lots of resources for free oss photos; https://dev.to/davidepacilio/50-free-tools-and-resources-to-create-awesome-user-interfaces-1c1b#photos

Now I would like to suggest using specifically a video footage for this as I wanna try that out and I think it will look awesome. Use; https://coverr.co/ search for videos of Toronto if you like. 😄 

If you have any questions feel free to ask. 😄

**Comment by SudharakaP** [comment]
@faithghlee : But of course if that fails or we cannot find a good video image, we can try the old fashion carousel as well. 😄
